<!-- generated by holo — edit the canonical source in core/, not this file -->
# Holocron Engineering Standards (Holocron context layer)

This file is generated by `holo` from the Holocron standards; edit the canonical source in the Holocron repo's `core/context/knowledge/`, not this file. It carries what "good" looks like at Holocron in a form an agent can act on. Sections marked *(fill per org)* are the ones each team completes; everything else applies org-wide.

## Architectural standards

- **Depend on abstractions, not concretions.** High-level modules take their dependencies as parameters; do not construct concrete implementations internally.
- **One concept per file.** One class, one module, one component. Keep files under ~300 lines — a longer file usually means the concept is doing too much.
- **Organize by feature, not by layer.** Co-locate the model, service, repository, and handler for a feature. Do not scatter related code across `models/`, `services/`, `repositories/`.
- **Small functions.** A function does one thing; if its name needs "and", split it. Aim for 0–3 parameters (more suggests a parameter object). Avoid boolean parameters that switch behaviour — use two clearly named functions. Return early with guard clauses to keep nesting shallow.
- **Naming carries intent.** Variables describe what they hold (`customerEmail`, not `data`); functions are verbs (`calculateShippingCost()`, not `process()`); booleans use `is/has/can/should`; constants are `SCREAMING_SNAKE_CASE`; classes are nouns (`OrderProcessor`, not `OrderHelper`).
- *(fill per org)* Holocron's approved patterns and the specific anti-patterns to avoid.

## Service catalogue

*(fill per org)* The services that already exist, so agents **integrate rather than rebuild**. For each: what it owns, its published contract, and how to call it. When a task needs a capability, check this catalogue before writing a new service; reinventing an existing Holocron service (auth, payments, entitlements, guest profile, notifications) is a review-blocking finding.

## Data classification

- Guest data is tiered. Treat **PII, payment data, and any data relating to minors** as restricted.
- **Never** put restricted data in logs, error messages, test fixtures, or diffs. Do not log passwords, tokens, API keys, PII, or card numbers.
- Restricted-tier data at rest uses KMS/HSM-backed storage with access limited to named individuals.
- Secrets are loaded from the environment or a secrets manager — **never hardcoded**.
- Database access is **parameterized** — no string interpolation into queries.
- *(fill per org)* Holocron's data tiers, retention rules, and the exact fields that count as restricted.

## Security requirements

- **Authentication:** OAuth2/OIDC with the authorization-code flow **+ PKCE** — never the implicit flow. JWTs use short expiry (≈15 min access, ≈7 day refresh); keep the access token in memory and the refresh token in an HttpOnly cookie. Server sessions use `HttpOnly`/`Secure`/`SameSite` cookies. API keys are scoped to minimum permissions and rotated.
- **Authorization:** verify the requesting user has access to the **specific resource** requested. Never trust client-provided ownership claims. Prefer RBAC for clear hierarchies, ABAC for context-dependent policies.
- **Input & output:** validate all external input at the boundary (type, length, range, format); encode output for its context (HTML, URL, JS, CSS); set a Content-Security-Policy. Once data crosses the boundary into a domain type, internal code does not re-validate.
- **Dependencies / supply chain:** maintain an SBOM, pin versions, scan weekly, prefer signed artifacts, and remove unused dependencies. Have an emergency path for critical CVEs.
- **Requires security review:** any change touching auth, authorization on a protected endpoint, secret handling, input validation, output encoding, file upload, CORS, rate limiting, or error-message disclosure.

## Golden paths

- The approved way to build a service, a pipeline, and a front end. *(fill per org — link the reference implementation for each.)*
- Match ceremony to risk: run `/scope` before building features, greenfield, spikes, and migrations; run `/plan` before features, refactors, and migrations. Hotfixes skip ceremony; the unit is still recorded.
- Roll out behind a **feature flag**, then canary, then full deploy for anything guest-facing or revenue-affecting. State the rollback in the scope.

## CI/CD conventions

Three quality gates:

- **Gate 1 — code review:** all unit tests pass · no new linter warnings · **code coverage does not decrease** · no high/critical security issues.
- **Gate 2 — integration:** integration and contract tests pass · performance baseline not regressed (a >10% degradation fails the gate).
- **Gate 3 — release:** e2e tests pass on staging · accessibility checks pass · no open P0/P1 defects · stakeholder sign-off.

*(fill per org)* How Holocron's Harness pipelines are structured and which gates are automated.

## Accessibility and brand

- Guest-facing accessibility standards are non-negotiable and are enforced at Gate 3.
- *(fill per org)* Disney brand and voice standards that guest-facing surfaces must meet.

## Testing standards

- **Unit** — one function/class in isolation, external dependencies mocked; runs in milliseconds on every commit; cover every public function with non-trivial logic.
- **Integration** — two or more components together with real dependencies where practical (test DB, local queue); runs in seconds on every PR; focus on API endpoints, service↔repository, and message flows.
- **End-to-end** — a full user workflow through the stack in a deployed/containerised environment; runs in minutes before release; **cap at ~20–30** (more means missing integration coverage), scoped to critical journeys (login, core CRUD, payment).
- Rough proportions: **~75% unit / ~20% integration / ~5% e2e.**
- Name tests `test_[function]_[scenario]_[expected_result]`.
- **Tests assert behaviour, not the implementation back to itself.** A test that only re-states the code, or asserts a mock returned what it was told to, is not coverage.
- A scope or plan written in ninety seconds with no open questions is theatre, not thinking — the AI-aware review checklist (`/verify`) exists to catch exactly this.

## Compliance

- **Data residency:** guest data stays in its region of origin (EU guest data stays in EU-region storage, etc.) unless a documented cross-border transfer mechanism is in place. *(fill per org)* Holocron's approved regions and transfer mechanisms.
- **Audit:** every read or write of restricted-tier data (see Data classification) is attributable to a named actor and is logged to an append-only, tamper-evident audit trail. Audit logs are themselves treated as restricted data.
- **Retention:** data is kept only as long as its documented retention policy requires, then deleted or anonymized on a schedule — not left to accumulate indefinitely. *(fill per org)* Holocron's retention schedules per data tier and the deletion/anonymization mechanism.
- **Regulatory scope:** *(fill per org)* which frameworks apply (e.g. GDPR, CCPA, COPPA for data relating to minors, PCI-DSS for payment data) and the specific controls each requires beyond the org-wide baseline above.
